### ISSUE TITLE
Please make Catppuccin version

### ISSUE THREAD

**Issue by DarkReaper231** [alvatip/Nordzy-cursors#6]
I switched from Nordic theme to Catppuccin and I have been using your cursor when using Nordic theme but now I am left pretty much with this only

https://github.com/catppuccin/cursors
I'm sure there are people who like those but to me personally, they are ugly. They are kinda bulky and hilarious, I don't know.
Your cursor feels more modern and has much more interesting and pleasant shape.

PS: They might accept your cursors under catppuccin organization

**Comment by DarkReaper231** [comment]
> Hey, I will have a look at these and will most likely create a variant/new project for these

Thank you very much

**Comment by Vibhav201** [comment]
@alvatip Thank you for this amazing cursor theme. I want these cursors to be ported to multiple colour schemes (including catppuccin) since I like many colour schemes and changing between them. 

How much work will it be to change the colour scheme of these cursors? Can you please give me any advice on how should I approach this? 

I hope you reply and give me some advice on this very soon.  :)

**Comment by alvatip** [comment]
@Vibhav201 
Thanks for the suggestion,
For Nordzy-cursor: I will update the script (minor update) + base theme which will allow this for Nordzy-cursors (linux only, will remove windows from the scripts for now since I had issue in the final result of animated icons)
For Nordzy-icon: I will have a look at your script and see how it could be adapted to Nordzy-icon ;)

This might take a bit of time because of holidays

**Comment by Vibhav201** [comment]
That's awesome. I'll be waiting.

> I want to achieve similar functionality and have a similar script for these Nordzy Icons.

I was referring to Nordzy cursors here as well actually. So, you can take your time with the icons lol.

I haven't really tried the icons yet but they look gorgeous. I'll be glad if you are able to make a script to change the icon colour schemes. I might switch to this set from Papirus if you make it possible.

Though I doubt that my script will provide much help lol because it's a rather simple script and changes only folder icon colours. Good Luck :)

**Comment by alvatip** [comment]
@Vibhav201 
I finished to update the script, will push the modification this afternoon. I still have to create readme for github page and help function for the script but it is fairly easy to use: 

Script is located under tools/custom_theme.sh
SVG template for the cursor is located under tools/svgs/nordzy-templates/Nordzy-cursors-template.svg (for static cursor) and Nordzy-cursors-spinner-template.svg (for animated cursors). 

Script works as follow:
./custom_theme.sh --name "Nordzy-catppuccin-latte-rosewater" --fill "#dc8a78" --border "#eff1f5" --accent "#eff1f5"  --purple "#1e66f5" --green "#40a02b" --red "#d20f39" --orange "#fe640b"

- --name = name of the new theme
- --fill = fill color (ex: black)
- --border = border color (ex: white)
- --accent = blue/turquoise color present in the spinner
- --purple/red/green/orange = replace these colors in the cursor theme (see where they are in Nordzy-cursors-template.svg)

if some value are not mentionned, default value will be given (the one used in Nordzy-cursors-template.svg/same for spinner)
then themes are stored in archives and can be installed with ./install.sh

I will try to look now where you should act with your script to change color of Nordzy-icon folder :wink: 

@DarkReaper231 using the newly created script I generated the cursor theme with catppuccin colors (all variant) and will push them this afternoon. Since this is a first draft, some stuff might need changes (color choice, ...), any feedback is always welcome.

**Comment by alvatip** [comment]
@Vibhav201 
For modification of folder in Nordzy: 
After installation, all folders are located under Nordzy/places (places @2X is just a symlink -> places). The icons you will very likely want to modify are located in Nordzy/places/scalable

The icons themselves have 3 layers: 
2 are forming the folder and 1 is for the symbol displayed on it (other stuff are shadows)
the 2 that are forming the folder use one color, it varies depending on the option used during installation but the default color is #81a1c1
Therefore to change the main color of the folder, simply using sed -i "s/color_to_replace/new_color/g" file.svg should do the trick

If you want your script to act earlier during the installation, let me know but I think that acting on the default color after a default installation is the easiest option :smile:

**Comment by DarkReaper231** [comment]
@alvatip pink body with either crust, base or surface0 border works pretty fine, did you make it so we can choose border color and stuff?

**Comment by Vibhav201** [comment]
All this is amazing. I will surely get back to you next week after trying the scripts. I am a bit busy this week.

**Comment by alvatip** [comment]
@DarkReaper231 with the custom script, custom cursor with you preferred color can be created quite easily,
I am uploading all the catppuccin theme I created, I believe one will fit but if needed you will be able to create your own

**Comment by alvatip** [comment]
@Vibhav201 
No worries :wink:

**Comment by Vibhav201** [comment]
Hey @alvatip, I checked out the script to change the colours and it works perfectly. But, I think that the blur shadow/glow of the cursors doesn't look that good. It makes the cursor less crisp imo. I think you should remove that glow effect from the cursors. Anyways, thanks a lot for the script.

**Comment by alvatip** [comment]
Hi @Vibhav201, glad to hear that it works perfectly,
I removed the shadows from the templates in my last commit :wink: 
Should have removed them a long time ago, some were not placed properly behind the cursors
